-- 코드를 입력하세요
-- ANIMAL_INS  동물 보호소에 들어온
-- ANIMAL_OUTS 동물 보호소에서 나간 
-- 일부 데이터 유실되어서 입양간 기록은 있는데 들어온 기록이 없음 
SELECT ANIMAL_OUTS.ANIMAL_ID ,ANIMAL_OUTS.NAME
FROM ANIMAL_INS 
RIGHT JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID IS NULL
ORDER BY ANIMAL_OUTS.ANIMAL_ID

