-- 코드를 입력하세요
-- ANIMAL_INS 들어온 애들 ANIMAL_OUTS나간애들 
-- 입양 못 간 친구들 중에 가장 오래 있었던 친구들 출력하는데 3명만 

SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME
FROM ANIMAL_OUTS
RIGHT JOIN ANIMAL_INS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_OUTS.ANIMAL_ID IS NULL
ORDER BY  ANIMAL_INS.DATETIME
LIMIT 3;


